# Generated by Django 5.1 on 2024-09-28 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_student_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='facultyID',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
