# Generated by Django 5.1 on 2024-09-29 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_faculty_phone_number_student_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='avatar.svg', upload_to='pics'),
        ),
    ]
