# Generated by Django 5.1 on 2024-09-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='country',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('NB', 'Non-binary'), ('O', 'Other'), ('PNS', 'Prefer not to say')], default='PNS', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='nationality',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='profile_image',
            field=models.ImageField(default='faculty.svg', upload_to='pics'),
        ),
    ]
