# Generated by Django 5.1 on 2024-09-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_faculty_profile_alter_faculty_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='profile_image',
            field=models.ImageField(default='faculty.svg', upload_to='pics'),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_image',
            field=models.ImageField(default='student.svg', upload_to='pics'),
        ),
    ]
