# Generated by Django 5.1 on 2024-09-29 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_faculty_profile_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
