# Generated by Django 5.1 on 2024-09-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_faculty_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
