# Generated by Django 5.1 on 2024-09-29 17:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_faculty_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Pincode must be a 6-digit number.', regex='^\\d{6}$')]),
        ),
    ]
