# Generated by Django 5.1 on 2024-10-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_faculty_pincode'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
