# Generated by Django 5.1 on 2024-08-31 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mtechMinorEval', '0002_remove_examinerevaluation_attendance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guideevaluation',
            old_name='examiner',
            new_name='guide',
        ),
    ]
