# Generated by Django 5.1 on 2024-08-31 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtechMinorEval', '0003_rename_examiner_guideevaluation_guide'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideevaluation',
            name='guide',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='examinerevaluation',
            name='examiner',
            field=models.ForeignKey(limit_choices_to={'profile__role': 'faculty'}, on_delete=django.db.models.deletion.CASCADE, to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='project',
            name='examiner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examiner_projects', to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='project',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guide_projects', to='users.faculty'),
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile',
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.student'),
        ),
        migrations.DeleteModel(
            name='Faculty',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
