# Generated by Django 5.1 on 2024-09-01 02:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtechMinorEval', '0004_alter_guideevaluation_guide_and_more'),
        ('users', '0003_faculty_email_profile_email_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guideevaluation',
            name='guide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.faculty'),
        ),
    ]
