# Generated by Django 5.1 on 2024-09-01 02:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtechMinorEval', '0005_alter_guideevaluation_guide'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProjectEvalSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('examiner_total_eval', models.PositiveIntegerField(default=0)),
                ('guide_total_eval', models.PositiveIntegerField(default=0)),
                ('is_satisfactory', models.BooleanField(default=False)),
                ('guide_name', models.CharField(max_length=255)),
                ('examiner_name', models.CharField(max_length=255)),
                ('student_rollno', models.CharField(max_length=20)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eval_summary', to='mtechMinorEval.project')),
            ],
        ),
    ]
