# Generated by Django 5.1 on 2024-09-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtechMinorEval', '0006_project_deadline_projectevalsummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectevalsummary',
            name='examiner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectevalsummary',
            name='guide_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='projectevalsummary',
            name='student_rollno',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
