# Generated by Django 5.1 on 2024-09-28 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtechMinorEval', '0008_alter_project_student'),
        ('users', '0004_student_cgpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinerevaluation',
            name='examiner',
            field=models.ForeignKey(blank=True, limit_choices_to={'profile__role': 'faculty'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='guideevaluation',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.faculty'),
        ),
    ]
