# Generated by Django 5.1 on 2024-10-01 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtechMinorEval', '0009_alter_examinerevaluation_examiner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ppt',
            field=models.FileField(blank=True, null=True, upload_to='mtechMinorEval/ppts/'),
        ),
    ]
