# Generated by Django 5.1 on 2024-10-02 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtechMinorEval', '0012_alter_projectevalsummary_examiner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectevalsummary',
            name='sn',
            field=models.CharField(default='n', editable=False, max_length=1),
        ),
    ]
