# Generated by Django 5.1 on 2024-10-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtechMinorEval', '0013_projectevalsummary_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='PathAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
